#!/usr/bin/env python3
"""
RAG Flow Context - Mutable state container for the RAG pipeline.

Passed through each stage of execute_rag_flow; stages read from and write to
the context. The orchestrator only creates the context and runs stages.
"""

from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional

from agent.rag.search_planner import SearchPlan


@dataclass
class RAGFlowContext:
    """Mutable context for the RAG pipeline. Stages mutate this object."""

    # Inputs (set once by orchestrator)
    question: str
    stream: bool
    show_details: bool
    comprehensive: bool
    stream_callback: Optional[Callable[..., Any]] = None
    max_iterations: Optional[int] = None  # Set from config in _stage_setup if None
    conversation_id: Optional[str] = None
    answer_mode: Optional[str] = None  # "direct", "standard", "detailed" — set after question analysis

    # Timing
    start_time: float = 0.0
    analysis_time: float = 0.0
    reasoning_time: float = 0.0  # NEW: Combined reasoning + analysis time
    search_time: float = 0.0
    generation_time: float = 0.0

    # Stage 2: Question analysis (NEW: now generated by combined reasoning stage)
    question_analysis: Optional[Dict[str, Any]] = None
    target_quarters: Optional[List[str]] = None
    early_return: Optional[Dict[str, Any]] = None  # If set, orchestrator yields and returns

    # Stage 2.1: Planning (NEW: reasoning now comes from combined stage)
    reasoning_result: Optional[Any] = None  # ReasoningResult from ReasoningPlanner
    reasoning_statement: Optional[str] = None
    search_plan: Optional[SearchPlan] = None

    # Stage 2.5 / 2.6 / 3.5: News & 10-K
    news_results: Optional[Dict[str, Any]] = None
    ten_k_results: List[Any] = field(default_factory=list)
    news_context_str: Optional[str] = None
    ten_k_context_str: Optional[str] = None

    # Stage 3: Transcript search
    skip_initial_transcript_search: bool = False
    individual_results: List[Dict[str, Any]] = field(default_factory=list)
    all_chunks: List[Dict[str, Any]] = field(default_factory=list)
    all_citations: List[Any] = field(default_factory=list)
    is_general_question: bool = False
    is_multi_ticker: bool = False
    tickers_to_process: List[str] = field(default_factory=list)
    target_quarter: Optional[str] = None

    # After context prep
    combined_citations: List[Any] = field(default_factory=list)

    # After iterative improvement
    improvement_results: Any = None  # tuple or error dict
    improvement_error: bool = False  # True if improvement returned error dict
    best_answer: Optional[str] = None
    best_confidence: float = 0.0
    best_citations: List[Any] = field(default_factory=list)
    best_context_chunks: List[str] = field(default_factory=list)
    best_chunks: List[Dict[str, Any]] = field(default_factory=list)
    evaluation_context: List[Dict[str, Any]] = field(default_factory=list)
    follow_up_questions_asked: List[str] = field(default_factory=list)
    accumulated_chunks: List[Dict[str, Any]] = field(default_factory=list)

    # Final (set by _stage_finalize)
    final_result: Optional[Dict[str, Any]] = None


@dataclass
class ImprovementState:
    """
    Mutable state for the iterative improvement loop.
    One loop iteration = evaluate → [maybe] search (transcript + news + follow-up) → [if new chunks] generate.
    """
    accumulated_chunks: List[Dict[str, Any]] = field(default_factory=list)
    accumulated_citations: List[Any] = field(default_factory=list)
    best_answer: Optional[str] = None
    best_confidence: float = 0.0
    best_citations: List[Any] = field(default_factory=list)
    best_context_chunks: List[str] = field(default_factory=list)
    best_chunks: List[Dict[str, Any]] = field(default_factory=list)
    evaluation_context: List[Dict[str, Any]] = field(default_factory=list)
    follow_up_questions_asked: List[str] = field(default_factory=list)
    # news/10-K context can be extended during iterations (e.g. iteration news merge)
    news_context: Optional[str] = None
    ten_k_context: Optional[str] = None
